apiVersion: v1
kind: ConfigMap
metadata:
  name: liferay-config
data:
  portal-ext.properties: |
    jdbc.default.driverClassName=com.mysql.jdbc.Driver
    jdbc.default.url=jdbc:mysql://mysql:3306/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
    jdbc.default.username=liferay
    jdbc.default.password=liferay

    web.server.host=liferay-argocd.com
    web.server.protocol=https
    virtual.hosts.valid.hosts=localhost,127.0.0.1,liferay-argocd.com,[::1],[0:0:0:0:0:0:0:1]
