apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liferay-mysql
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Dhruvlunagaria/liferay_mysql.git
    targetRevision: HEAD
    path: .  # Adjust this path if needed, ensure it contains kustomization.yaml
    kustomize:
      namePrefix: liferay-
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true


