apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
        - name: liferay
          image: liferay/portal:7.4.3.112-ga112
          ports:
            - containerPort: 8080
          env:
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
              value: jdbc:mysql://mysql:3306/liferay?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
              value: liferay
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
              value: liferay
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
